version: "3.5"

services:
  backend-blue:
    image: gitlab.praktikum-services.ru:5050/std-012-005/sausage-store/sausage-backend:latest
    container_name: sausage-store-backend-blue
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: sausage-store-backend
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 3s
      timeout: 1s
      start_period: 20s
      retries: 6
    networks:
      - sausage-store
  backend-green:
    image: gitlab.praktikum-services.ru:5050/std-012-005/sausage-store/sausage-backend:latest
    container_name: sausage-store-backend-green
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: sausage-store-backend
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 3s
      timeout: 1s
      start_period: 20s
      retries: 6
    networks:
      - sausage-store
  backend-report:
    #build:
    #  context: backend-report
    #  dockerfile: Dockerfile
    image: gitlab.praktikum-services.ru:5050/std-012-005/sausage-store/sausage-backend-report:latest
    container_name: sausage-store-backend-report
    environment:
      DB: ${DB}
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-012-005/sausage-store/sausage-frontend:latest
    container_name: sausage-store-frontend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - sausage-store
#  frontend:
#    image: gitlab.praktikum-services.ru:5050/std-012-005/sausage-store/sausage-frontend:latest
#    container_name: sausage-store-frontend
#    ports:
#      - "80:80"
#    networks:
#      - sausage-store

networks:
  sausage-store:
